namespace AppSage.Providers.Repository
{
    public class FileExtensionClassification
    {
        public string Extension { get; set; }
        public string Category { get; set; }
        public string SubCategory { get; set; }
        public string Description { get; set; }

        public bool LineCountable { get; set; }

        public static string UNKOWN = ConstString.UNKNOWN;
        public FileExtensionClassification(string extension, string technology, string category, string description)
        {
            Extension = extension;
            SubCategory = technology;
            Category = category;
            Description = description;
        }

        public FileExtensionClassification(string extension, string technology, string category, bool lineCountable, string description)
        {
            Extension = extension;
            SubCategory = technology;
            Category = category;
            Description = description;
            LineCountable = lineCountable;
        }

        public static Dictionary<string, FileExtensionClassification> GetComprehensiveFileTypes()
        {
            var fileTypes = new Dictionary<string, FileExtensionClassification>
            {
                { UNKOWN, new FileExtensionClassification(ConstString.UNKNOWN, ConstString.UNKNOWN, ConstString.UNCATEGORIZED, false, ConstString.UNKNOWN) },
                // Programming Languages - Core & General - Line countable
                { ".c", new FileExtensionClassification(".c", "C", "Code", true, "C Source File") },
                { ".cpp", new FileExtensionClassification(".cpp", "C++", "Code", true, "C++ Source File") },
                { ".h", new FileExtensionClassification(".h", "C/C++", "Code", true, "C/C++ Header File") },
                { ".hpp", new FileExtensionClassification(".hpp", "C++", "Code", true, "C++ Header File") },
                { ".cs", new FileExtensionClassification(".cs", "C#", "Code", true, "C# Source File") },
                { ".csx", new FileExtensionClassification(".csx", "C#", "Code", true, "C# Script File") },
                { ".py", new FileExtensionClassification(".py", "Python", "Code", true, "Python Source File") },
                { ".pyc", new FileExtensionClassification(".pyc", "Python", "Code", false, "Python Compiled File") },
                { ".pyd", new FileExtensionClassification(".pyd", "Python", "Code", false, "Python Extension Module") },
                { ".pyo", new FileExtensionClassification(".pyo", "Python", "Code", false, "Python Optimized Bytecode") },
                { ".pyw", new FileExtensionClassification(".pyw", "Python", "Code", true, "Python GUI Script") },
                { ".java", new FileExtensionClassification(".java", "Java", "Code", true, "Java Source File") },
                { ".class", new FileExtensionClassification(".class", "Java", "Code", false, "Java Class File") },
                { ".jar", new FileExtensionClassification(".jar", "Java", "Package", false, "Java Archive File") },
                { ".js", new FileExtensionClassification(".js", "JavaScript", "Code", true, "JavaScript Source File") },
                { ".jsx", new FileExtensionClassification(".jsx", "JavaScript", "Code", true, "React JSX File") },
                { ".ts", new FileExtensionClassification(".ts", "TypeScript", "Code", true, "TypeScript Source File") },
                { ".tsx", new FileExtensionClassification(".tsx", "TypeScript", "Code", true, "TypeScript JSX File") },
                { ".rb", new FileExtensionClassification(".rb", "Ruby", "Code", true, "Ruby Source File") },
                { ".erb", new FileExtensionClassification(".erb", "Ruby", "Code", true, "Ruby Embedded HTML") },
                { ".go", new FileExtensionClassification(".go", "Go", "Code", true, "Go Source File") },
                { ".rs", new FileExtensionClassification(".rs", "Rust", "Code", true, "Rust Source File") },
                { ".php", new FileExtensionClassification(".php", "PHP", "Code", true, "PHP Source File") },
                { ".php5", new FileExtensionClassification(".php5", "PHP", "Code", true, "PHP 5 Source File") },
                { ".phtml", new FileExtensionClassification(".phtml", "PHP", "Code", true, "PHP HTML Template") },
                { ".swift", new FileExtensionClassification(".swift", "Swift", "Code", true, "Swift Source File") },
                { ".kt", new FileExtensionClassification(".kt", "Kotlin", "Code", true, "Kotlin Source File") },
                { ".kts", new FileExtensionClassification(".kts", "Kotlin", "Code", true, "Kotlin Script File") },
                { ".groovy", new FileExtensionClassification(".groovy", "Groovy", "Code", true, "Groovy Source File") },
                { ".scala", new FileExtensionClassification(".scala", "Scala", "Code", true, "Scala Source File") },
                { ".pm", new FileExtensionClassification(".pm", "Perl", "Code", true, "Perl Module File") },
                { ".t", new FileExtensionClassification(".t", "Perl", "Code", true, "Perl Test File") },
                { ".lua", new FileExtensionClassification(".lua", "Lua", "Code", true, "Lua Source File") },
                { ".r", new FileExtensionClassification(".r", "R", "Code", true, "R Source File") },
                { ".dart", new FileExtensionClassification(".dart", "Dart", "Code", true, "Dart Source File") },
                { ".clj", new FileExtensionClassification(".clj", "Clojure", "Code", true, "Clojure Source File") },
                { ".fs", new FileExtensionClassification(".fs", "F#", "Code", true, "F# Source File") },
                { ".fsx", new FileExtensionClassification(".fsx", "F#", "Code", true, "F# Script File") },
                { ".fsi", new FileExtensionClassification(".fsi", "F#", "Code", true, "F# Signature File") },
                { ".hs", new FileExtensionClassification(".hs", "Haskell", "Code", true, "Haskell Source File") },
                { ".lhs", new FileExtensionClassification(".lhs", "Haskell", "Code", true, "Literate Haskell Source") },
                { ".jl", new FileExtensionClassification(".jl", "Julia", "Code", true, "Julia Source File") },
                { ".erl", new FileExtensionClassification(".erl", "Erlang", "Code", true, "Erlang Source File") },
                { ".ex", new FileExtensionClassification(".ex", "Elixir", "Code", true, "Elixir Source File") },
                { ".exs", new FileExtensionClassification(".exs", "Elixir", "Code", true, "Elixir Script File") },
                { ".elm", new FileExtensionClassification(".elm", "Elm", "Code", true, "Elm Source File") },
                { ".coffee", new FileExtensionClassification(".coffee", "CoffeeScript", "Code", true, "CoffeeScript Source File") },
                { ".ls", new FileExtensionClassification(".ls", "LiveScript", "Code", true, "LiveScript Source File") },

                // Web & Frontend - Line countable
                { ".html", new FileExtensionClassification(".html", "HTML", "Web", true, "HTML Document") },
                { ".htm", new FileExtensionClassification(".htm", "HTML", "Web", true, "HTML Document") },
                { ".xhtml", new FileExtensionClassification(".xhtml", "HTML", "Web", true, "XHTML Document") },
                { ".css", new FileExtensionClassification(".css", "CSS", "Web", true, "Cascading Style Sheet") },
                { ".scss", new FileExtensionClassification(".scss", "SASS", "Web", true, "SASS Style Sheet") },
                { ".sass", new FileExtensionClassification(".sass", "SASS", "Web", true, "SASS Style Sheet") },
                { ".less", new FileExtensionClassification(".less", "LESS", "Web", true, "LESS Style Sheet") },
                { ".styl", new FileExtensionClassification(".styl", "Stylus", "Web", true, "Stylus Style Sheet") },
                { ".vue", new FileExtensionClassification(".vue", "Vue.js", "Web", true, "Vue Component") },
                { ".svelte", new FileExtensionClassification(".svelte", "Svelte", "Web", true, "Svelte Component") },
                { ".hbs", new FileExtensionClassification(".hbs", "Handlebars", "Web", true, "Handlebars Template") },
                { ".mustache", new FileExtensionClassification(".mustache", "Mustache", "Web", true, "Mustache Template") },
                { ".ejs", new FileExtensionClassification(".ejs", "EJS", "Web", true, "Embedded JavaScript Template") },
                { ".pug", new FileExtensionClassification(".pug", "Pug", "Web", true, "Pug Template") },
                { ".jade", new FileExtensionClassification(".jade", "Pug", "Web", true, "Jade Template (legacy Pug)") },

                // Shell & Scripting - Line countable
                { ".sh", new FileExtensionClassification(".sh", "Shell", "Script", true, "Shell Script") },
                { ".bash", new FileExtensionClassification(".bash", "Bash", "Script", true, "Bash Script") },
                { ".zsh", new FileExtensionClassification(".zsh", "Zsh", "Script", true, "Z Shell Script") },
                { ".fish", new FileExtensionClassification(".fish", "Fish", "Script", true, "Fish Shell Script") },
                { ".bat", new FileExtensionClassification(".bat", "Batch", "Script", true, "Windows Batch File") },
                { ".cmd", new FileExtensionClassification(".cmd", "Batch", "Script", true, "Windows Command File") },
                { ".ps1", new FileExtensionClassification(".ps1", "PowerShell", "Script", true, "PowerShell Script") },
                { ".psm1", new FileExtensionClassification(".psm1", "PowerShell", "Script", true, "PowerShell Module") },
                { ".psd1", new FileExtensionClassification(".psd1", "PowerShell", "Script", true, "PowerShell Data File") },
                { ".vbs", new FileExtensionClassification(".vbs", "VBScript", "Script", true, "Visual Basic Script") },
                { ".awk", new FileExtensionClassification(".awk", "AWK", "Script", true, "AWK Script") },
                { ".sed", new FileExtensionClassification(".sed", "SED", "Script", true, "SED Script") },

                // Config & Data Formats - Line countable
                { ".json", new FileExtensionClassification(".json", "JSON", "Data", true, "JSON Data File") },
                { ".jsonl", new FileExtensionClassification(".jsonl", "JSON", "Data", true, "JSON Lines File") },
                { ".jsonc", new FileExtensionClassification(".jsonc", "JSON", "Data", true, "JSON with Comments") },
                { ".yaml", new FileExtensionClassification(".yaml", "YAML", "Data", true, "YAML Data File") },
                { ".yml", new FileExtensionClassification(".yml", "YAML", "Data", true, "YAML Data File") },
                { ".xml", new FileExtensionClassification(".xml", "XML", "Data", true, "XML Data File") },
                { ".xsd", new FileExtensionClassification(".xsd", "XML", "Data", true, "XML Schema Definition") },
                { ".xsl", new FileExtensionClassification(".xsl", "XSLT", "Data", true, "XSL Transformation File") },
                { ".xslt", new FileExtensionClassification(".xslt", "XSLT", "Data", true, "XSL Transformation File") },
                { ".ini", new FileExtensionClassification(".ini", "INI", "Config", true, "Configuration File") },
                { ".toml", new FileExtensionClassification(".toml", "TOML", "Config", true, "TOML Configuration File") },
                { ".conf", new FileExtensionClassification(".conf", "Config", "Config", true, "Configuration File") },
                { ".properties", new FileExtensionClassification(".properties", "Properties", "Config", true, "Java Properties File") },
                { ".env", new FileExtensionClassification(".env", "Environment", "Config", true, "Environment Variables File") },
                { ".csv", new FileExtensionClassification(".csv", "CSV", "Data", true, "Comma-Separated Values File") },
                { ".tsv", new FileExtensionClassification(".tsv", "TSV", "Data", true, "Tab-Separated Values File") },
                { ".md", new FileExtensionClassification(".md", "Markdown", "Documentation", true, "Markdown File") },
                { ".markdown", new FileExtensionClassification(".markdown", "Markdown", "Documentation", true, "Markdown File") },
                { ".mdx", new FileExtensionClassification(".mdx", "MDX", "Documentation", true, "Markdown with JSX") },
                { ".rst", new FileExtensionClassification(".rst", "reStructuredText", "Documentation", true, "reStructuredText File") },
                { ".tex", new FileExtensionClassification(".tex", "LaTeX", "Documentation", true, "LaTeX Document") },
                { ".adoc", new FileExtensionClassification(".adoc", "AsciiDoc", "Documentation", true, "AsciiDoc Document") },
                { ".asciidoc", new FileExtensionClassification(".asciidoc", "AsciiDoc", "Documentation", true, "AsciiDoc Document") },

                // Database & Data Processing - Line countable for SQL, not for binary databases
                { ".sql", new FileExtensionClassification(".sql", "SQL", "Database", true, "SQL Script") },
                { ".sqlite", new FileExtensionClassification(".sqlite", "SQLite", "Database", false, "SQLite Database") },
                { ".db", new FileExtensionClassification(".db", "Database", "Database", false, "Database File") },
                { ".mdb", new FileExtensionClassification(".mdb", "Access", "Database", false, "Microsoft Access Database") },
                { ".accdb", new FileExtensionClassification(".accdb", "Access", "Database", false, "Microsoft Access Database") },
                { ".gql", new FileExtensionClassification(".gql", "GraphQL", "Data", true, "GraphQL File") },
                { ".graphql", new FileExtensionClassification(".graphql", "GraphQL", "Data", true, "GraphQL File") },
                { ".cypher", new FileExtensionClassification(".cypher", "Cypher", "Database", true, "Cypher Query Language") },
                { ".cql", new FileExtensionClassification(".cql", "CQL", "Database", true, "Cassandra Query Language") },

                // DevOps & Infrastructure - Line countable
                { ".dockerfile", new FileExtensionClassification(".dockerfile", "Docker", "DevOps", true, "Dockerfile") },
                { ".dockerignore", new FileExtensionClassification(".dockerignore", "Docker", "DevOps", true, "Docker Ignore File") },
                { ".tf", new FileExtensionClassification(".tf", "Terraform", "DevOps", true, "Terraform Configuration") },
                { ".tfvars", new FileExtensionClassification(".tfvars", "Terraform", "DevOps", true, "Terraform Variables") },
                { ".hcl", new FileExtensionClassification(".hcl", "HCL", "DevOps", true, "HashiCorp Configuration Language") },
                { ".vagrantfile", new FileExtensionClassification(".vagrantfile", "Vagrant", "DevOps", true, "Vagrant Configuration") },
                { ".bicep", new FileExtensionClassification(".bicep", "Bicep", "DevOps", true, "Azure Bicep Template") },
                { ".k8s.yaml", new FileExtensionClassification(".k8s.yaml", "Kubernetes", "DevOps", true, "Kubernetes Configuration") },
                { ".helm", new FileExtensionClassification(".helm", "Helm", "DevOps", true, "Helm Chart") },
                { ".cf.json", new FileExtensionClassification(".cf.json", "CloudFormation", "DevOps", true, "AWS CloudFormation Template") },
                { ".cf.yaml", new FileExtensionClassification(".cf.yaml", "CloudFormation", "DevOps", true, "AWS CloudFormation Template") },
                { ".cdk.ts", new FileExtensionClassification(".cdk.ts", "AWS CDK", "DevOps", true, "AWS CDK TypeScript Code") },
                { ".pulumi.yaml", new FileExtensionClassification(".pulumi.yaml", "Pulumi", "DevOps", true, "Pulumi Configuration") },
                { ".gitlab-ci.yml", new FileExtensionClassification(".gitlab-ci.yml", "GitLab CI", "DevOps", true, "GitLab CI Configuration") },
                { ".travis.yml", new FileExtensionClassification(".travis.yml", "Travis CI", "DevOps", true, "Travis CI Configuration") },
                { ".appveyor.yml", new FileExtensionClassification(".appveyor.yml", "AppVeyor", "DevOps", true, "AppVeyor CI Configuration") },
                { ".circleci", new FileExtensionClassification(".circleci", "CircleCI", "DevOps", true, "CircleCI Configuration") },
                { ".jenkins", new FileExtensionClassification(".jenkins", "Jenkins", "DevOps", true, "Jenkins Configuration") },
                { ".jenkinsfile", new FileExtensionClassification(".jenkinsfile", "Jenkins", "DevOps", true, "Jenkins Pipeline") },
                { ".azure-pipelines.yml", new FileExtensionClassification(".azure-pipelines.yml", "Azure DevOps", "DevOps", true, "Azure Pipelines Configuration") },
                { ".github", new FileExtensionClassification(".github", "GitHub", "DevOps", true, "GitHub Configuration") },
                { ".goreleaser.yml", new FileExtensionClassification(".goreleaser.yml", "GoReleaser", "DevOps", true, "GoReleaser Configuration") },

                // Mobile Development - Line countable source code, not for binary files
                { ".m", new FileExtensionClassification(".m", "Objective-C", "Mobile", true, "Objective-C Source File") },
                { ".mm", new FileExtensionClassification(".mm", "Objective-C++", "Mobile", true, "Objective-C++ Source File") },
                { ".kotlin", new FileExtensionClassification(".kotlin", "Kotlin", "Mobile", true, "Kotlin Source File") },
                { ".xcodeproj", new FileExtensionClassification(".xcodeproj", "Xcode", "Mobile", false, "Xcode Project") },
                { ".pbxproj", new FileExtensionClassification(".pbxproj", "Xcode", "Mobile", true, "Xcode Project File") },
                { ".storyboard", new FileExtensionClassification(".storyboard", "iOS", "Mobile", true, "iOS Storyboard") },
                { ".xib", new FileExtensionClassification(".xib", "iOS", "Mobile", true, "iOS Interface Builder") },
                { ".plist", new FileExtensionClassification(".plist", "iOS/macOS", "Mobile", true, "Property List File") },
                { ".gradle", new FileExtensionClassification(".gradle", "Gradle", "Build", true, "Gradle Build File") },
                { ".gradlew", new FileExtensionClassification(".gradlew", "Gradle", "Build", true, "Gradle Wrapper") },
                { ".apk", new FileExtensionClassification(".apk", "Android", "Mobile", false, "Android Package") },
                { ".ipa", new FileExtensionClassification(".ipa", "iOS", "Mobile", false, "iOS App Package") },
                { ".entitlements", new FileExtensionClassification(".entitlements", "iOS", "Mobile", true, "iOS Entitlements File") },

                // Build & Package Management - Line countable
                { ".csproj", new FileExtensionClassification(".csproj", ".NET", "Build", true, "C# Project File") },
                { ".vbproj", new FileExtensionClassification(".vbproj", ".NET", "Build", true, "VB.NET Project File") },
                { ".fsproj", new FileExtensionClassification(".fsproj", ".NET", "Build", true, "F# Project File") },
                { ".sln", new FileExtensionClassification(".sln", ".NET", "Build", true, "Visual Studio Solution") },
                { ".nuspec", new FileExtensionClassification(".nuspec", "NuGet", "Package", true, "NuGet Specification") },
                { ".nupkg", new FileExtensionClassification(".nupkg", "NuGet", "Package", false, "NuGet Package") },
                { ".rake", new FileExtensionClassification(".rake", "Ruby", "Build", true, "Rake Build File") },
                { ".gemspec", new FileExtensionClassification(".gemspec", "Ruby", "Package", true, "Ruby Gem Specification") },
                { ".pom.xml", new FileExtensionClassification(".pom.xml", "Maven", "Build", true, "Maven Project Object Model") },
                { ".sbt", new FileExtensionClassification(".sbt", "SBT", "Build", true, "Scala Build Tool") },
                { ".ivy.xml", new FileExtensionClassification(".ivy.xml", "Ivy", "Build", true, "Apache Ivy Configuration") },
                { ".ant.xml", new FileExtensionClassification(".ant.xml", "Ant", "Build", true, "Apache Ant Build File") },
                { ".bazel", new FileExtensionClassification(".bazel", "Bazel", "Build", true, "Bazel Build File") },
                { ".bzl", new FileExtensionClassification(".bzl", "Bazel", "Build", true, "Bazel Build File") },
                { ".cargo.toml", new FileExtensionClassification(".cargo.toml", "Cargo", "Package", true, "Rust Cargo Package") },
                { ".cabal", new FileExtensionClassification(".cabal", "Cabal", "Package", true, "Haskell Cabal Package") },
                { ".mix.exs", new FileExtensionClassification(".mix.exs", "Mix", "Package", true, "Elixir Mix Package") },
                { ".makefile", new FileExtensionClassification(".makefile", "Make", "Build", true, "Makefile") },
                { ".cmake", new FileExtensionClassification(".cmake", "CMake", "Build", true, "CMake Build File") },
                { ".gyp", new FileExtensionClassification(".gyp", "GYP", "Build", true, "Generate Your Projects") },
                { ".ninja", new FileExtensionClassification(".ninja", "Ninja", "Build", true, "Ninja Build File") },
                { ".vcxproj", new FileExtensionClassification(".vcxproj", "Visual C++", "Build", true, "Visual C++ Project") },
                { ".pro", new FileExtensionClassification(".pro", "QMake/Prolog", "Build/Code", true, "QMake Project File or Prolog Source File") },
                { ".pri", new FileExtensionClassification(".pri", "QMake", "Build", true, "QMake Include File") },
                { ".plugin", new FileExtensionClassification(".plugin", "Plugin", "Config", true, "Plugin Configuration") },

                // Package Configurations - Line countable
                { ".npmrc", new FileExtensionClassification(".npmrc", "npm", "Package", true, "npm Configuration") },
                { ".yarnrc", new FileExtensionClassification(".yarnrc", "Yarn", "Package", true, "Yarn Configuration") },
                { ".nvmrc", new FileExtensionClassification(".nvmrc", "nvm", "Config", true, "Node ReferenceVersion Manager") },
                { ".package.json", new FileExtensionClassification(".package.json", "npm", "Package", true, "npm Package Configuration") },
                { ".package-lock.json", new FileExtensionClassification(".package-lock.json", "npm", "Package", true, "npm Lock File") },
                { ".yarn.lock", new FileExtensionClassification(".yarn.lock", "Yarn", "Package", true, "Yarn Lock File") },
                { ".bower.json", new FileExtensionClassification(".bower.json", "Bower", "Package", true, "Bower Package Configuration") },
                { ".composer.json", new FileExtensionClassification(".composer.json", "Composer", "Package", true, "PHP Composer Package") },
                { ".composer.lock", new FileExtensionClassification(".composer.lock", "Composer", "Package", true, "PHP Composer Lock") },
                { ".gemfile", new FileExtensionClassification(".gemfile", "Ruby", "Package", true, "Ruby Gem Dependencies") },
                { ".gemfile.lock", new FileExtensionClassification(".gemfile.lock", "Ruby", "Package", true, "Ruby Gem Lock") },
                { ".pipfile", new FileExtensionClassification(".pipfile", "Python", "Package", true, "Python Package Requirements") },
                { ".pipfile.lock", new FileExtensionClassification(".pipfile.lock", "Python", "Package", true, "Python Package Lock") },
                { ".pyproject.toml", new FileExtensionClassification(".pyproject.toml", "Python", "Package", true, "Python Project Configuration") },
                { ".poetry.lock", new FileExtensionClassification(".poetry.lock", "Poetry", "Package", true, "Python Poetry Lock") },
                { ".requirements.txt", new FileExtensionClassification(".requirements.txt", "Python", "Package", true, "Python Requirements") },
                { ".setup.py", new FileExtensionClassification(".setup.py", "Python", "Package", true, "Python Package Setup") },
                { ".gopkg.toml", new FileExtensionClassification(".gopkg.toml", "Go", "Package", true, "Go Package Configuration") },
                { ".cargo.lock", new FileExtensionClassification(".cargo.lock", "Cargo", "Package", true, "Rust Cargo Lock") },
                { ".nuget.config", new FileExtensionClassification(".nuget.config", "NuGet", "Package", true, "NuGet Configuration") },

                // Legacy & Specialized - Line countable
                { ".vb", new FileExtensionClassification(".vb", "Visual Basic", "Code", true, "Visual Basic Source File") },
                { ".bas", new FileExtensionClassification(".bas", "BASIC", "Code", true, "BASIC Source File") },
                { ".frm", new FileExtensionClassification(".frm", "Visual Basic", "Code", true, "Visual Basic Form") },
                { ".cls", new FileExtensionClassification(".cls", "Visual Basic", "Code", true, "Visual Basic Class Module") },
                { ".asm", new FileExtensionClassification(".asm", "Assembly", "Code", true, "Assembly Source File") },
                { ".s", new FileExtensionClassification(".s", "Assembly", "Code", true, "Assembly Source File") },
                { ".cobol", new FileExtensionClassification(".cobol", "COBOL", "Code", true, "COBOL Source File") },
                { ".cob", new FileExtensionClassification(".cob", "COBOL", "Code", true, "COBOL Source File") },
                { ".cbl", new FileExtensionClassification(".cbl", "COBOL", "Code", true, "COBOL Source File") },
                { ".fortran", new FileExtensionClassification(".fortran", "Fortran", "Code", true, "Fortran Source File") },
                { ".f", new FileExtensionClassification(".f", "Fortran", "Code", true, "Fortran Source File") },
                { ".f90", new FileExtensionClassification(".f90", "Fortran", "Code", true, "Fortran 90 Source File") },
                { ".f95", new FileExtensionClassification(".f95", "Fortran", "Code", true, "Fortran 95 Source File") },
                { ".ada", new FileExtensionClassification(".ada", "Ada", "Code", true, "Ada Source File") },
                { ".adb", new FileExtensionClassification(".adb", "Ada", "Code", true, "Ada Body File") },
                { ".ads", new FileExtensionClassification(".ads", "Ada", "Code", true, "Ada Specification File") },
                { ".d", new FileExtensionClassification(".d", "D", "Code", true, "D Programming Language") },
                { ".pas", new FileExtensionClassification(".pas", "Pascal", "Code", true, "Pascal Source File") },
                { ".dpr", new FileExtensionClassification(".dpr", "Delphi", "Code", true, "Delphi Project") },
                { ".dfm", new FileExtensionClassification(".dfm", "Delphi", "Code", true, "Delphi Form") },
                { ".bb", new FileExtensionClassification(".bb", "BlitzBASIC", "Code", true, "BlitzBASIC Source File") },
                { ".bmx", new FileExtensionClassification(".bmx", "BlitzMax", "Code", true, "BlitzMax Source File") },
                { ".ahk", new FileExtensionClassification(".ahk", "AutoHotkey", "Script", true, "AutoHotkey Script") },
                { ".au3", new FileExtensionClassification(".au3", "AutoIt", "Script", true, "AutoIt Script") },
                { ".ml", new FileExtensionClassification(".ml", "OCaml", "Code", true, "OCaml Source File") },
                { ".mli", new FileExtensionClassification(".mli", "OCaml", "Code", true, "OCaml Interface File") },
                { ".pl1", new FileExtensionClassification(".pl1", "PL/1", "Code", true, "PL/1 Source File") },
                { ".m4", new FileExtensionClassification(".m4", "M4", "Script", true, "M4 Macro Processor") },
                { ".lisp", new FileExtensionClassification(".lisp", "Lisp", "Code", true, "Lisp Source File") },
                { ".cl", new FileExtensionClassification(".cl", "Common Lisp", "Code", true, "Common Lisp Source File") },
                { ".el", new FileExtensionClassification(".el", "Emacs Lisp", "Code", true, "Emacs Lisp Source File") },
                { ".scm", new FileExtensionClassification(".scm", "Scheme", "Code", true, "Scheme Source File") },
                { ".tcl", new FileExtensionClassification(".tcl", "Tcl", "Code", true, "Tcl Script") },
                { ".prolog", new FileExtensionClassification(".prolog", "Prolog", "Code", true, "Prolog Source File") },
                { ".pl", new FileExtensionClassification(".pl", "Prolog/Perl", "Code", true, "Prolog/Perl Source File") },
                { ".lex", new FileExtensionClassification(".lex", "Lex", "Code", true, "Lexical Analyzer Specification") },
                { ".y", new FileExtensionClassification(".y", "Yacc", "Code", true, "Yacc Grammar") },
                { ".yacc", new FileExtensionClassification(".yacc", "Yacc", "Code", true, "Yacc Grammar") },

                // ReferenceVersion Control & Project - Line countable
                { ".gitignore", new FileExtensionClassification(".gitignore", "Git", "VCS", true, "Git Ignore File") },
                { ".gitattributes", new FileExtensionClassification(".gitattributes", "Git", "VCS", true, "Git Attributes File") },
                { ".gitmodules", new FileExtensionClassification(".gitmodules", "Git", "VCS", true, "Git Submodules File") },
                { ".gitkeep", new FileExtensionClassification(".gitkeep", "Git", "VCS", true, "Git Keep File") },
                { ".git-blame-ignore-revs", new FileExtensionClassification(".git-blame-ignore-revs", "Git", "VCS", true, "Git Blame Ignore File") },
                { ".hgignore", new FileExtensionClassification(".hgignore", "Mercurial", "VCS", true, "Mercurial Ignore File") },
                { ".svnignore", new FileExtensionClassification(".svnignore", "SVN", "VCS", true, "SVN Ignore File") },
                { ".editorconfig", new FileExtensionClassification(".editorconfig", "EditorConfig", "Config", true, "Editor Configuration") },
                { ".eslintrc", new FileExtensionClassification(".eslintrc", "ESLint", "Config", true, "ESLint Configuration") },
                { ".eslintignore", new FileExtensionClassification(".eslintignore", "ESLint", "Config", true, "ESLint Ignore File") },
                { ".prettierrc", new FileExtensionClassification(".prettierrc", "Prettier", "Config", true, "Prettier Configuration") },
                { ".prettierignore", new FileExtensionClassification(".prettierignore", "Prettier", "Config", true, "Prettier Ignore File") },
                { ".stylelintrc", new FileExtensionClassification(".stylelintrc", "StyleLint", "Config", true, "Style Linter Configuration") },
                { ".jshintrc", new FileExtensionClassification(".jshintrc", "JSHint", "Config", true, "JSHint Configuration") },
                { ".babelrc", new FileExtensionClassification(".babelrc", "Babel", "Config", true, "Babel Configuration") },
                { ".browserslistrc", new FileExtensionClassification(".browserslistrc", "Browserslist", "Config", true, "Browser Compatibility") },
                
                // Documents & Media - Line countable for text files, not for binary formats
                { ".txt", new FileExtensionClassification(".txt", "Text", "Document", true, "Plain Text File") },
                { ".rtf", new FileExtensionClassification(".rtf", "Rich Text", "Document", true, "Rich Text Format") },
                { ".pdf", new FileExtensionClassification(".pdf", "PDF", "Document", false, "Portable Document Format") },
                { ".doc", new FileExtensionClassification(".doc", "Word", "Document", false, "Microsoft Word Document (Legacy)") },
                { ".docx", new FileExtensionClassification(".docx", "Word", "Document", false, "Microsoft Word Document") },
                { ".xls", new FileExtensionClassification(".xls", "Excel", "Document", false, "Microsoft Excel Spreadsheet (Legacy)") },
                { ".xlsx", new FileExtensionClassification(".xlsx", "Excel", "Document", false, "Microsoft Excel Spreadsheet") },
                { ".ppt", new FileExtensionClassification(".ppt", "PowerPoint", "Document", false, "Microsoft PowerPoint (Legacy)") },
                { ".pptx", new FileExtensionClassification(".pptx", "PowerPoint", "Document", false, "Microsoft PowerPoint") },
                { ".jpg", new FileExtensionClassification(".jpg", "JPEG", "Media", false, "JPEG Image") },
                { ".jpeg", new FileExtensionClassification(".jpeg", "JPEG", "Media", false, "JPEG Image") },
                { ".png", new FileExtensionClassification(".png", "PNG", "Media", false, "PNG Image") },
                { ".gif", new FileExtensionClassification(".gif", "GIF", "Media", false, "GIF Image") },
                { ".svg", new FileExtensionClassification(".svg", "SVG", "Media", true, "Scalable Vector Graphics") },
                { ".ico", new FileExtensionClassification(".ico", "Icon", "Media", false, "Icon File") },
                { ".webp", new FileExtensionClassification(".webp", "WebP", "Media", false, "WebP Image") },
                { ".mp3", new FileExtensionClassification(".mp3", "MP3", "Media", false, "MP3 Audio File") },
                { ".mp4", new FileExtensionClassification(".mp4", "MP4", "Media", false, "MP4 Video File") },
                { ".wav", new FileExtensionClassification(".wav", "WAV", "Media", false, "Waveform Audio File") },
                { ".ogg", new FileExtensionClassification(".ogg", "OGG", "Media", false, "Ogg Vorbis Audio File") },
                { ".webm", new FileExtensionClassification(".webm", "WebM", "Media", false, "WebM Video File") },
                { ".ttf", new FileExtensionClassification(".ttf", "Font", "Media", false, "TrueType Font") },
                { ".otf", new FileExtensionClassification(".otf", "Font", "Media", false, "OpenType Font") },
                { ".woff", new FileExtensionClassification(".woff", "Font", "Media", false, "Web Open Font Format") },
                { ".woff2", new FileExtensionClassification(".woff2", "Font", "Media", false, "Web Open Font Format 2") },

                // Binary & Executable Files - Not line countable
                { ".dll", new FileExtensionClassification(".dll", "DLL", "Binary", false, "Dynamic Link Library") },
                { ".exe", new FileExtensionClassification(".exe", "EXE", "Binary", false, "Executable File") },
                { ".so", new FileExtensionClassification(".so", "SO", "Binary", false, "Shared Object Library") },
                { ".dylib", new FileExtensionClassification(".dylib", "DYLIB", "Binary", false, "Dynamic Library (macOS)") },
                { ".a", new FileExtensionClassification(".a", "Static Library", "Binary", false, "Static Library") },
                { ".lib", new FileExtensionClassification(".lib", "LIB", "Binary", false, "Library File") },
                { ".obj", new FileExtensionClassification(".obj", "OBJ", "Binary", false, "Object File") },
                { ".o", new FileExtensionClassification(".o", "Object", "Binary", false, "Object File") },
                { ".bin", new FileExtensionClassification(".bin", "Binary", "Binary", false, "Binary File") },
                { ".dat", new FileExtensionClassification(".dat", "Data", "Binary", false, "Data File") },
                { ".iso", new FileExtensionClassification(".iso", "ISO", "Binary", false, "Disc Image") },
                { ".img", new FileExtensionClassification(".img", "Disk Image", "Binary", false, "Disk Image File") },
                { ".dmg", new FileExtensionClassification(".dmg", "Disk Image", "Binary", false, "macOS Disk Image") },
                { ".sys", new FileExtensionClassification(".sys", "System", "Binary", false, "System File") },
                { ".com", new FileExtensionClassification(".com", "COM", "Binary", false, "Command File") },
                { ".msi", new FileExtensionClassification(".msi", "Installer", "Binary", false, "Microsoft Installer Package") },
                { ".appx", new FileExtensionClassification(".appx", "Installer", "Binary", false, "Windows App Package") },
                { ".deb", new FileExtensionClassification(".deb", "Installer", "Binary", false, "Debian Package") },
                { ".rpm", new FileExtensionClassification(".rpm", "Installer", "Binary", false, "Red Hat Package") },
                { ".tar", new FileExtensionClassification(".tar", "Archive", "Binary", false, "Tape Archive") },
                { ".zip", new FileExtensionClassification(".zip", "Archive", "Binary", false, "Zip Archive") },
                { ".gz", new FileExtensionClassification(".gz", "Archive", "Binary", false, "Gzip Archive") },
                { ".7z", new FileExtensionClassification(".7z", "Archive", "Binary", false, "7-Zip Archive") },
                { ".rar", new FileExtensionClassification(".rar", "Archive", "Binary", false, "RAR Archive") },
                { ".pdb", new FileExtensionClassification(".pdb", "Debug", "Binary", false, "Program Database") },
                { ".ilk", new FileExtensionClassification(".ilk", "Debug", "Binary", false, "Incremental Linking File") },
                { ".exp", new FileExtensionClassification(".exp", "Debug", "Binary", false, "Export File") },
            };
            
            return fileTypes;
        }
    }
}
